# Generated by Django 3.1 on 2020-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CO', 'Contributor'), ('TR', 'Translator'), ('VI', 'Videographer')], default='CO', max_length=2, verbose_name='role'),
        ),
    ]
