# Generated by Django 3.1 on 2020-08-21 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('platform_url', models.CharField(blank=True, default='', max_length=50, verbose_name='platform url')),
                ('platform_type', models.CharField(blank=True, choices=[('YT', 'Youtube'), ('PT', 'Peertube')], default='', max_length=2, verbose_name='platform type')),
                ('video_id', models.CharField(blank=True, default='', max_length=50, verbose_name='video id')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='title')),
                ('descr', models.TextField(blank=True, default='', verbose_name='description')),
                ('lang', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian')], max_length=2, verbose_name='language')),
                ('tags', models.CharField(blank=True, default='', help_text='Utilisez une virgule « , » pour saisir plusieurs tags.', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False, verbose_name='done')),
                ('votes', models.IntegerField(blank=True, default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.source')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='email vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='verification code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères, « . », « + », « - » et « _ ».', max_length=150, unique=True, validators=[main.models.CustomUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, choices=[('TR', 'Transcript'), ('SUB', 'Subtitle')], default='', max_length=3, verbose_name='group')),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian')], max_length=2, verbose_name='language')),
                ('upload', models.FileField(upload_to=main.models.file_upload, verbose_name='file')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('title', models.CharField(default='', max_length=100, verbose_name='title')),
                ('descr', models.TextField(blank=True, default='', verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.channel_directory_path)),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'unique_together': {('video', 'user')},
            },
        ),
    ]
